name: EY Pipeline

on:
  push:
    branches:
      - EY-CTFGROUP-01

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install application dependencies
        run: npm install

      - name: Install Semgrep
        run: python3 -m pip install semgrep

      - name: Run Semgrep Scan
        run: semgrep --config auto --error || true
